max_size = 180000  # per file cap for write_text_snapshot

[modes.tight]
include = [
  ".snapshot.toml",
  "README.md",
  "README_FOR_AI.md",
  "COMMANDS_REFERENCE.md",
  "CHANGELOG.md",
  "MODULES.md",
  "pyproject.toml",
  "src/xsarena/cli/main.py",
  "src/xsarena/cli/registry.py",
  "src/xsarena/cli/context.py",
  "src/xsarena/cli/cmds_run.py",
  "src/xsarena/cli/cmds_authoring.py",
  "src/xsarena/cli/cmds_jobs.py",
  "src/xsarena/cli/cmds_snapshot.py",
  "src/xsarena/cli/cmds_health.py",
  "src/xsarena/cli/cmds_tools.py",
  "src/xsarena/cli/cmds_unified_settings.py",
  "src/xsarena/core/prompt.py",
  "src/xsarena/core/prompt_runtime.py",
  "src/xsarena/core/config.py",
  "src/xsarena/core/state.py",
  "src/xsarena/core/v2_orchestrator/orchestrator.py",
  "src/xsarena/core/v2_orchestrator/specs.py",
  "src/xsarena/core/jobs/model.py",
  "src/xsarena/core/jobs/executor.py",
  "src/xsarena/core/jobs/scheduler.py",
  "src/xsarena/core/jobs/store.py",
  "src/xsarena/core/jobs/helpers.py",
  "src/xsarena/core/engine.py",
  "src/xsarena/core/backends/__init__.py",
  "src/xsarena/core/redact.py",
  "src/xsarena/utils/snapshot_simple.py",
  "src/xsarena/utils/helpers.py",
  "src/xsarena/bridge_v2/api_server.py",
  "directives/base/zero2hero.md",
  "directives/system/plan_from_seeds.md",
  "directives/_rules/rules.merged.md",
  "directives/manifest.yml",
  "docs/USAGE.md",
  "docs/OPERATING_MODEL.md",
  "docs/ARCHITECTURE.md",
  "docs/COMMANDS_CHEATSHEET.md",
]
exclude = [
  ".git/**", ".svn/**", ".hg/**", ".idea/**", ".vscode/**",
  "venv/**", ".venv/**", "__pycache__/**",
  ".pytest_cache/**", ".mypy_cache/**", ".ruff_cache/**", ".cache/**",
  "*.pyc", "*.pyo", "*.pyd", "*.log", "logs/**",
  ".xsarena/**", "*.egg-info/**", ".ipynb_checkpoints/**",
  "books/**", "review/**", "tests/**", "examples/**", "packaging/**", "pipelines/**", "tools/**", "scripts/**",
  "repo_flat.txt", "xsa_snapshot*.txt", "xsa_snapshot*.zip", "xsa_debug_report*.txt", "snapshot_chunks/**"
]

[modes.minimal]
# keep existing defaults (from code), or add here if you want to override

[modes.standard]
# keep existing defaults (from code), or add here if you want to override

[modes.full]
# keep existing defaults (from code), or add here if you want to override
