max_size = 180000  # per file cap for write_text_snapshot

[modes.tight]
include = [
  ".snapshot.toml",
  "README.md",
  "COMMANDS_REFERENCE.md",
  "pyproject.toml",
  "src/xsarena/cli/main.py",
  "src/xsarena/cli/registry.py",
  "src/xsarena/cli/context.py",
  "src/xsarena/cli/cmds_run.py",
  "src/xsarena/core/config.py",
  "src/xsarena/core/state.py",
  "src/xsarena/core/jobs/model.py",
  "src/xsarena/core/jobs/executor.py",
  "src/xsarena/core/jobs/scheduler.py",
  "src/xsarena/core/jobs/store.py",
  "docs/USAGE.md",
  "docs/OPERATING_MODEL.md",
]
exclude = [
  ".git/**", ".svn/**", ".hg/**", ".idea/**", ".vscode/**",
  "venv/**", ".venv/**", "__pycache__/**",
  ".pytest_cache/**", ".mypy_cache/**", ".ruff_cache/**", ".cache/**",
  "*.pyc", "*.pyo", "*.pyd", "*.log", "logs/**",
  ".xsarena/**", "*.egg-info/**", ".ipynb_checkpoints/**",
  "books/**", "review/**", "tests/**", "examples/**", "packaging/**", "pipelines/**", "tools/**", "scripts/**",
  "repo_flat.txt", "xsa_snapshot*.txt", "xsa_snapshot*.zip", "xsa_debug_report*.txt", "snapshot_chunks/**"
]

[modes.minimal]
# keep existing defaults (from code), or add here if you want to override

[modes.standard]
# keep existing defaults (from code), or add here if you want to override

[modes.full]
# keep existing defaults (from code), or add here if you want to override