[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "lmastudio"
version = "0.1.0"
description = "AI-powered writing and coding studio"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "LMASudio Team"}
]
dependencies = [
    "typer>=0.9.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "aiohttp>=3.8.0",
    "pydantic>=2.0.0"
]

[project.optional-dependencies]
tui = [
    "textual>=0.40.0"
]
dev = [
    "pytest>=7.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
    "black>=23.0.0"
]
watch = [
    "watchdog>=3.0.0"
]

[project.scripts]
lmastudio = "src.lmastudio.cli.main:run"
lmastudio-bridge = "src.lmastudio.bridge.server:main"

[project.urls]
Homepage = "https://github.com/your-username/lmastudio"
Repository = "https://github.com/your-username/lmastudio"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B", "SIM"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]