name: Bug Report
about: Create a report to help us improve
title: '[Bug] '
labels: 'bug'
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce this?
      description: Please provide the exact command or steps you ran
      placeholder: "1. Run 'xsarena ...'\n2. See error"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of XSArena are you using?
      placeholder: Output of 'xsarena version'
    validations:
      required: true