"""Simple extractors for checklists and related study aids.

This module focuses on extracting checklist-like items from Markdown texts.
It supports:
- Task lists: "- [ ] item", "* [x] done", etc.
- Bulleted/numbered lines under headings containing 'Checklist'
- Deduplication with order preserved

Exports (commonly used by CLI/tests):
- CHECKLIST_TASK_PATTERN
- CHECKLIST_BULLET_PATTERN
- CHECKLIST_NUMBERED_PATTERN
- extract_checklists_from_text(text) -> list[str]
- extract_checklists_from_book(path) -> list[str]
- extract_checklist_items(text) -> list[str]  # alias to extract_checklists_from_text
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable, List

# Task-style markdown lines (with optional checkbox):
# - [ ] item
# - [x] done
# * [ ] another
CHECKLIST_TASK_PATTERN = re.compile(r"^\s*[-*]\s*\[\s*[xX ]\s*\]\s*(?P<text>.+?)\s*$")

# Plain bullets (accept under checklist sections):
# - item
# * item
CHECKLIST_BULLET_PATTERN = re.compile(r"^\s*[-*]\s+(?P<text>.+?)\s*$")

# Numbered items (accept under checklist sections):
# 1. item
# 2) item
CHECKLIST_NUMBERED_PATTERN = re.compile(r"^\s*\d+\s*[.)]\s+(?P<text>.+?)\s*$")

_HEADING_PATTERN = re.compile(r"^\s*#{1,6}\s+(?P<title>.+?)\s*$", re.UNICODE)


def _dedupe_preserve_order(items: Iterable[str]) -> List[str]:
    """Deduplicate while preserving first occurrence order."""
    seen = set()
    out: List[str] = []
    for it in items:
        key = it.strip()
        if key and key not in seen:
            out.append(key)
            seen.add(key)
    return out


def extract_checklists_from_text(text: str) -> List[str]:
    """Extract checklist items from markdown text.

    Rules:
    - Always include checkbox task lines anywhere ("- [ ] item", "* [x] item").
    - Additionally, within any heading whose title contains 'checklist'
      (case-insensitive), also include plain bullets and numbered lines.
    """
    if not text:
        return []

    lines = text.splitlines()
    within_checklist_section = False
    out: List[str] = []

    for ln in lines:
        # Track headings
        m_h = _HEADING_PATTERN.match(ln)
        if m_h:
            title = (m_h.group("title") or "").strip().lower()
            within_checklist_section = "checklist" in title
            continue

        # Always accept explicit task lines
        m_task = CHECKLIST_TASK_PATTERN.match(ln)
        if m_task:
            out.append(m_task.group("text").strip())
            continue

        # If under a checklist section, accept bullets/numbered
        if within_checklist_section:
            m_bul = CHECKLIST_BULLET_PATTERN.match(ln)
            if m_bul:
                out.append(m_bul.group("text").strip())
                continue
            m_num = CHECKLIST_NUMBERED_PATTERN.match(ln)
            if m_num:
                out.append(m_num.group("text").strip())
                continue

    return _dedupe_preserve_order(out)


def extract_checklists_from_book(path: str | Path) -> List[str]:
    """Read a markdown file and extract checklist items."""
    p = Path(path)
    if not p.exists():
        return []
    content = p.read_text(encoding="utf-8", errors="replace")
    return extract_checklists_from_text(content)


# Back-compat alias used by some callers/tests
def extract_checklist_items(text: str) -> List[str]:
    """Alias for extract_checklists_from_text()."""
    return extract_checklists_from_text(text)


def generate_checklist_report(items: List[str], source_path: str) -> str:
    """Generate a markdown report from extracted checklist items."""
    report = "# Checklist Report\n\n"
    report += f"**Source:** {source_path}\n\n"
    report += f"**Total Items:** {len(items)}\n\n"

    if items:
        report += "## Checklist Items\n\n"
        for i, item in enumerate(items, 1):
            report += f"{i}. {item}\n"
        report += "\n"
    else:
        report += "No checklist items found.\n\n"

    report += "---\n*Generated by XSArena checklist extractor*\n"
    return report


class ChecklistItem:
    """Represents a checklist item with section, content, original text, and line number."""

    def __init__(self, section: str, item: str, original: str, line: int):
        self.section = section
        self.item = item
        self.original = original
        self.line = line

    def __repr__(self):
        return f"ChecklistItem(section='{self.section}', item='{self.item}', line={self.line})"

    def __eq__(self, other):
        if not isinstance(other, ChecklistItem):
            return False
        return (self.section, self.item, self.line) == (
            other.section,
            other.item,
            other.line,
        )


# Imperative verb patterns for action items
IMPERATIVE_VERBS = [
    "add",
    "configure",
    "initialize",
    "start",
    "verify",
    "run",
    "test",
    "deploy",
    "check",
    "update",
    "set",
    "install",
    "follow",
    "enable",
    "disable",
    "create",
    "delete",
    "modify",
    "change",
    "adjust",
    "document",
    "contact",
    "restart",
    "apply",
    "execute",
    "perform",
    "complete",
    "finish",
    "implement",
    "setup",
    "establish",
    "define",
    "specify",
    "prepare",
    "organize",
    "arrange",
    "plan",
    "design",
    "develop",
    "build",
    "construct",
    "assemble",
    "compile",
    "debug",
    "fix",
    "resolve",
    "solve",
    "address",
    "handle",
    "manage",
    "control",
    "monitor",
    "track",
    "measure",
    "evaluate",
    "assess",
    "review",
    "inspect",
    "examine",
    "analyze",
    "study",
    "research",
    "investigate",
    "explore",
    "discover",
    "identify",
    "recognize",
    "acknowledge",
    "accept",
    "confirm",
    "validate",
    "verify",
    "assure",
    "guarantee",
    "ensure",
    "secure",
    "protect",
    "maintain",
    "preserve",
    "sustain",
    "support",
    "assist",
    "help",
    "aid",
    "facilitate",
    "enable",
    "empower",
    "authorize",
    "permit",
    "allow",
    "grant",
    "provide",
    "supply",
    "deliver",
    "distribute",
    "share",
    "communicate",
    "inform",
    "notify",
    "advise",
    "suggest",
    "recommend",
    "propose",
    "advocate",
    "promote",
    "encourage",
    "motivate",
    "inspire",
    "urge",
    "push",
    "drive",
    "lead",
    "guide",
    "direct",
    "steer",
    "navigate",
    "pilot",
    "control",
    "manage",
]

IMPERATIVE_PATTERN = re.compile(
    r"^\s*[-*]\s+(" + "|".join(IMPERATIVE_VERBS) + r")\s+(?P<text>.+)$", re.IGNORECASE
)


def extract_checklists(text: str) -> List[ChecklistItem]:
    """Extract checklist items from markdown text with section info."""
    if not text:
        return []

    lines = text.splitlines()
    current_section = "Introduction"
    items: List[ChecklistItem] = []
    section_line_map = {}  # Map sections to starting line numbers

    for i, ln in enumerate(lines):
        # Track headings to identify sections
        heading_match = _HEADING_PATTERN.match(ln)
        if heading_match:
            current_section = (heading_match.group("title") or "").strip()
            section_line_map[current_section] = i + 1
            continue

        # Check for task list items
        task_match = CHECKLIST_TASK_PATTERN.match(ln)
        if task_match:
            text_content = task_match.group("text").strip()
            items.append(
                ChecklistItem(current_section, text_content, ln.strip(), i + 1)
            )
            continue

        # Check for bullet list items
        bullet_match = CHECKLIST_BULLET_PATTERN.match(ln)
        if bullet_match:
            text_content = bullet_match.group("text").strip()
            # Also check for imperative verbs
            if IMPERATIVE_PATTERN.match(ln):
                items.append(
                    ChecklistItem(current_section, text_content, ln.strip(), i + 1)
                )
            elif "checklist" in current_section.lower():
                # Accept bullets under checklist sections
                items.append(
                    ChecklistItem(current_section, text_content, ln.strip(), i + 1)
                )
            continue

        # Check for numbered list items
        numbered_match = CHECKLIST_NUMBERED_PATTERN.match(ln)
        if numbered_match:
            text_content = numbered_match.group("text").strip()
            items.append(
                ChecklistItem(current_section, text_content, ln.strip(), i + 1)
            )
            continue

    return items


def group_checklist_items_by_section(
    items: List[ChecklistItem],
) -> dict[str, List[ChecklistItem]]:
    """Group checklist items by their section."""
    grouped = {}
    for item in items:
        if item.section not in grouped:
            grouped[item.section] = []
        grouped[item.section].append(item)
    return grouped


def normalize_checklist_items(items: List[ChecklistItem]) -> List[ChecklistItem]:
    """Normalize checklist items by removing duplicates while preserving order."""
    seen = set()
    result = []
    for item in items:
        # Create a key based on section and item text to identify duplicates
        key = (item.section, item.item.lower().strip())
        if key not in seen:
            seen.add(key)
            result.append(item)
    return result


def extract_checklists_from_file(path: str | Path) -> List[ChecklistItem]:
    """Read a markdown file and extract checklist items with section info."""
    p = Path(path)
    if not p.exists():
        return []
    content = p.read_text(encoding="utf-8", errors="replace")
    return extract_checklists(content)
